### ISSUE TITLE
Investigate reuse datawolf's postgresql instance for maestro service

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/maestro-service#26]

**Comment by navarroc** [comment]
What is needed here? I don't believe there is any limitation to re-using the postgres that is already running within the cluster. It would simply be a matter of creating a postgres user and either importing a DB dump or running the commands to create an empty table.

**Comment by longshuicy** [comment]
> What is needed here? I don't believe there is any limitation to re-using the postgres that is already running within the cluster. It would simply be a matter of creating a postgres user and either importing a DB dump or running the commands to create an empty table.

How would maestro connect to that existing postgres? what would be the port/username/password?

**Comment by navarroc** [comment]
Yes, I think @ywkim312 just needs to inject into the environment the postgres connection information so it's in the environment and then map those variables to what maestro reads. That's what we do for DataWolf.

**Comment by ywkim312** [comment]
> Yes, I think @ywkim312 just needs to inject into the environment the postgres connection information so it's in the environment and then map those variables to what maestro reads. That's what we do for DataWolf.

correct

**Comment by longshuicy** [comment]
it's finished
