### ISSUE TITLE
Investigate why maestro service is down

### ISSUE THREAD

**Issue by longshuicy** [IN-CORE/maestro-service#38]
File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column steps.updated_at does not exist
LINE 1: ...S steps_substep_id, steps.status AS steps_status, steps.upda...

**Comment by robkooper** [comment]
this was an error due to the maestro service running an old image. Updated the deployment to ALWAYS pull.

**Comment by ywkim312** [comment]
> this was an error due to the maestro service running an old image. Updated the deployment to ALWAYS pull.

Were there any Maestro update? I haven't heard anything since I deployed it from very long time ago.
